[versions]

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.9.3" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version = "1.4.0" }
androidx-camera-core = { module = "androidx.camera:camera-core", version = "1.4.0" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version = "1.4.0" }
androidx-camera-view = { module = "androidx.camera:camera-view", version = "1.4.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.0" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.15.0" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version = "1.3.7" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.8.7" }
play-services-location = { module = "com.google.android.gms:play-services-location", version = "21.3.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.14" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version = "1.2.1" }

[plugins]
android-application = { id = "com.android.application", version = "8.5.2" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.0.0" }
